services:
  juris-facil-pg:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: juris_facil
    ports:
      - 5434:5432
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
